import pandas as pd
import numpy as np
class StrategyAgent:
    """
    Agent responsible for analyzing data and generating trade hypotheses.
    """
    def __init__(self, strategy_params: dict = None):
        self.params = strategy_params or {
            "rsi_oversold": 30,
            "rsi_overbought": 70,
            "macd_use_signal": True
        }

    def evaluate_strategies(self, inputs: dict, state: dict):
        # Retrieve data generated by MarketAnalystAgent
        market_data = state.get("analyze_market", {}).get("market_data", {})
        
        print(f"[StrategyAgent] Evaluating strategies on {len(market_data)} assets...")
        hypotheses = []
        
        for asset, tf_data in market_data.items():
            # Example logic based on the plan
            if asset in ["SPY", "QQQ"] and "15m" in tf_data:
                # Mean Reversion on 15m
                df = tf_data["15m"]
                if not df.empty and 'RSI' in df.columns:
                    last_rsi = df['RSI'].iloc[-1].item() if not pd.isna(df['RSI'].iloc[-1].item()) else 50
                    current_price = df['Close'].iloc[-1].item() if not pd.isna(df['Close'].iloc[-1].item()) else 0
                    
                    oversold = self.params.get("rsi_oversold", 30)
                    overbought = self.params.get("rsi_overbought", 70)
                    
                    if last_rsi < oversold:
                        hypotheses.append({
                            "asset": asset,
                            "strategy": f"MeanReversion (RSI < {oversold})",
                            "direction": "long",
                            "price": current_price
                        })
                    elif last_rsi > overbought:
                        hypotheses.append({
                            "asset": asset,
                            "strategy": f"MeanReversion (RSI > {overbought})",
                            "direction": "short",
                            "price": current_price
                        })
            elif asset == "BTC-USD" and "1h" in tf_data:
                # Breakout on 1h
                df = tf_data["1h"]
                if not df.empty and 'MACD' in df.columns and 'MACD_Signal' in df.columns:
                    last_macd = df['MACD'].iloc[-1].item() if not pd.isna(df['MACD'].iloc[-1].item()) else 0
                    last_signal = df['MACD_Signal'].iloc[-1].item() if not pd.isna(df['MACD_Signal'].iloc[-1].item()) else 0
                    current_price = df['Close'].iloc[-1].item() if not pd.isna(df['Close'].iloc[-1].item()) else 0
                    
                    if last_macd > last_signal:
                        hypotheses.append({
                            "asset": asset,
                            "strategy": "Breakout (MACD Bullish Cross)",
                            "direction": "long",
                            "price": current_price
                        })
                    elif last_macd < last_signal:
                        hypotheses.append({
                            "asset": asset,
                            "strategy": "Breakout (MACD Bearish Cross)",
                            "direction": "short",
                            "price": current_price
                        })
            elif asset in ["GLD", "USO"] and "4h" in tf_data:
                # Trend Following on 4h
                df = tf_data["4h"]
                if not df.empty and 'EMA_20' in df.columns and 'EMA_50' in df.columns:
                    last_ema20 = df['EMA_20'].iloc[-1].item() if not pd.isna(df['EMA_20'].iloc[-1].item()) else 0
                    last_ema50 = df['EMA_50'].iloc[-1].item() if not pd.isna(df['EMA_50'].iloc[-1].item()) else 0
                    current_price = df['Close'].iloc[-1].item() if not pd.isna(df['Close'].iloc[-1].item()) else 0
                    
                    if last_ema20 > last_ema50:
                        hypotheses.append({
                            "asset": asset,
                            "strategy": "TrendFollowing (EMA20 > EMA50)",
                            "direction": "long",
                            "price": current_price
                        })
                    elif last_ema20 < last_ema50:
                        hypotheses.append({
                            "asset": asset,
                            "strategy": "TrendFollowing (EMA20 < EMA50)",
                            "direction": "short",
                            "price": current_price
                        })
                    
                    
        return {"hypotheses": hypotheses}

    @staticmethod
    def generate_vectorized_signals(df: pd.DataFrame, strategy_type: str = "RSI", **params) -> pd.Series:
        """
        Generador de señales vectorizadas para usar en VectorizedBacktester (Hyperopt).
        Devuelve una pd.Series con 1 (Long), -1 (Short) y 0 (Flat).
        """
        signals = pd.Series(0, index=df.index)
        
        if strategy_type == "RSI":
            oversold = params.get("rsi_oversold", 30)
            overbought = params.get("rsi_overbought", 70)
            if 'RSI' in df.columns:
                signals = np.where(df['RSI'] < oversold, 1, np.where(df['RSI'] > overbought, -1, 0))
                
        elif strategy_type == "MACD":
            if 'MACD' in df.columns and 'MACD_Signal' in df.columns:
                signals = np.where(df['MACD'] > df['MACD_Signal'], 1, -1)
                
        elif strategy_type == "EMA_CROSS":
            if 'EMA_20' in df.columns and 'EMA_50' in df.columns:
                signals = np.where(df['EMA_20'] > df['EMA_50'], 1, -1)
                
        return pd.Series(signals, index=df.index)
