import pandas as pd

class StrategyAgent:
    """
    Agent responsible for analyzing data and generating trade hypotheses.
    """
    def evaluate_strategies(self, inputs: dict, state: dict):
        # Retrieve data generated by MarketAnalystAgent
        market_data = state.get("analyze_market", {}).get("market_data", {})
        
        print(f"[StrategyAgent] Evaluating strategies on {len(market_data)} assets...")
        hypotheses = []
        
        for asset, tf_data in market_data.items():
            # Example logic based on the plan
            if asset in ["SPY", "QQQ"] and "15m" in tf_data:
                # Mean Reversion on 15m
                df = tf_data["15m"]
                if not df.empty:
                    # Mock strategy output for architecture demonstration
                    hypotheses.append({
                        "asset": asset,
                        "strategy": "MeanReversion",
                        "direction": "long",
                        "price": df['Close'].iloc[-1].item() if not pd.isna(df['Close'].iloc[-1].item()) else 0
                    })
            elif asset == "BTC-USD" and "1h" in tf_data:
                # Breakout on 1h
                df = tf_data["1h"]
                if not df.empty:
                    hypotheses.append({
                        "asset": asset,
                        "strategy": "Breakout",
                        "direction": "long",
                        "price": df['Close'].iloc[-1].item() if not pd.isna(df['Close'].iloc[-1].item()) else 0
                    })
            elif asset in ["GLD", "USO"] and "4h" in tf_data:
                # Trend Following on 4h
                df = tf_data["4h"]
                if not df.empty:
                    hypotheses.append({
                        "asset": asset,
                        "strategy": "TrendFollowing",
                        "direction": "long",
                        "price": df['Close'].iloc[-1].item() if not pd.isna(df['Close'].iloc[-1].item()) else 0
                    })
                    
        return {"hypotheses": hypotheses}
